onlyBuiltDependencies:
  - '@swc/core'
  - cwebp-bin
  - giflossy
  - jpegtran-bin
  - mozjpeg
  - pngquant-bin
  - sharp
  - zopflipng-bin

overrides:
  braces@<2.3.1: '>=2.3.1'
  braces@<3.0.3: '>=3.0.3'
  cross-spawn@<6.0.6: '>=6.0.6'
  decompress@<4.2.1: '>=4.2.1'
  got@<11.8.5: '>=11.8.5'
  http-cache-semantics@<4.1.1: '>=4.1.1'
  micromatch@<4.0.8: '>=4.0.8'
  semver-regex@<3.1.3: '>=3.1.3'
  semver-regex@<3.1.4: '>=3.1.4'
  semver@<5.7.2: '>=5.7.2'
  trim-newlines@<3.0.1: '>=3.0.1'
  tunnel-agent@<0.6.0: '>=0.6.0'
